name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2' # ensure you're using the same ruby version
        bundler-version: '2.3.26' # pin to a stable bundler version
        bundler-cache: true
    - name: Install gems
      run: |
        bundle install --deployment --without development test
    - name: Build the site
      run: bundle exec jekyll build
    - name: Deploy the site
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout gh-pages || git checkout --orphan gh-pages
        rm -rf *
        cp -r _site/* .
        git add .
        git commit -m "Deploy site" || echo "No changes to commit"
        git push origin gh-pages --force
