name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: false
    - name: Install Bundler and clean environment
      run: |
        gem uninstall -i $(bundle config path --global) uri --all --force || echo "No existing uri gem"
        gem install bundler:2.3.26
    - name: Install gems
      run: |
        bundle install --force
    - name: Build the site
      run: |
        bundle exec jekyll build || (echo "Jekyll build failed"; exit 1)
    - name: Deploy the site
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout gh-pages || git checkout --orphan gh-pages
        rm -rf *
        cp -r _site/* . || (echo "No files in _site to copy"; exit 1)
        git add .
        git commit -m "Deploy site" || echo "No changes to commit"
        git push origin gh-pages --force
