name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: false
    - name: Install ImageMagick
      run: |
        sudo apt-get update && sudo apt-get install -y imagemagick
    - name: Install Bundler and clean environment
      run: |
        gem uninstall -i $(bundle config path --global) uri --all --force || echo "No existing uri gem"
        gem install bundler:2.3.26
    - name: Install gems
      run: |
        bundle install --force
    - name: Build the site
      run: |
        bundle exec jekyll build --verbose --trace > jekyll_build_output.txt 2>&1 || (cat jekyll_build_output.txt && echo "Jekyll build failed. See output above." && exit 1)
        echo "Jekyll build supposedly succeeded. Output captured in jekyll_build_output.txt"
        cat jekyll_build_output.txt
    - name: Check _site directory
      run: |
        if [ ! -d "_site" ]; then
          echo "Error: _site directory does not exist."
          exit 1
        fi
        if [ -z "$(ls -A _site)" ]; then
          echo "Error: _site directory is empty."
          exit 1
        fi
        echo "_site directory exists and is not empty."
    - name: Upload Jekyll build log
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: jekyll-build-log
        path: jekyll_build_output.txt
    - name: Deploy the site
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout gh-pages || git checkout --orphan gh-pages
        rm -rf *
        cp -r _site/* . || (echo "No files in _site to copy"; exit 1)
        git add .
        git commit -m "Deploy site" || echo "No changes to commit"
        git push origin gh-pages --force
